

TESTPATH=test_cases/
TESTS=$(TESTPATH)1-FullIns_3.col -e\
			$(TESTPATH)1-FullIns_4.col -e\
			$(TESTPATH)2-FullIns_3.col -e\
			$(TESTPATH)2-FullIns_4.col -e\
			$(TESTPATH)3-FullIns_3.col -e\
			$(TESTPATH)4-FullIns_3.col -e\
			$(TESTPATH)5-FullIns_3.col -e\
			$(TESTPATH)1-Insertions_4.col -e\
			$(TESTPATH)2-Insertions_3.col -e\
			$(TESTPATH)3-Insertions_3.col -e\
			$(TESTPATH)4-Insertions_3.col -e\
			$(TESTPATH)anna.col -e\
			$(TESTPATH)ash331GPIA.col -e\
			$(TESTPATH)ash608GPIA.col -e\
			$(TESTPATH)ash958GPIA.col -e\
			$(TESTPATH)david.col -e\
			$(TESTPATH)DSJC125.1.col -e\
			$(TESTPATH)DSJC125.5.col -e\
			$(TESTPATH)DSJC125.9.col -e\
			$(TESTPATH)DSJC250.9.col -e\
			$(TESTPATH)DSJR500.1c.col -e\
			$(TESTPATH)DSJR500.1.col -e\
			$(TESTPATH)DSJR500.5.col -e\
			$(TESTPATH)flat300_28_0.col -e\
			$(TESTPATH)fpsol2.i.1.col -e\
			$(TESTPATH)fpsol2.i.2.col -e\
			$(TESTPATH)fpsol2.i.3.col -e\
			$(TESTPATH)games120.col -e\
			$(TESTPATH)homer.col -e\
			$(TESTPATH)huck.col -e\
			$(TESTPATH)inithx.i.1.col -e\
			$(TESTPATH)inithx.i.2.col -e\
			$(TESTPATH)inithx.i.3.col -e\
			$(TESTPATH)jean.col -e\
			$(TESTPATH)le450_15a.col -e\
			$(TESTPATH)le450_25a.col -e\
			$(TESTPATH)le450_25b.col -e\
			$(TESTPATH)le450_5c.col -e\
			$(TESTPATH)le450_5d.col -e\
			$(TESTPATH)miles1000.col -e\
			$(TESTPATH)miles1500.col -e\
			$(TESTPATH)miles250.col -e\
			$(TESTPATH)miles500.col -e\
			$(TESTPATH)miles750.col -e\
			$(TESTPATH)mug100_1.col -e\
			$(TESTPATH)mug100_25.col -e\
			$(TESTPATH)mug88_1.col -e\
			$(TESTPATH)mug88_25.col -e\
			$(TESTPATH)mulsol.i.1.col -e\
			$(TESTPATH)mulsol.i.2.col -e\
			$(TESTPATH)mulsol.i.3.col -e\
			$(TESTPATH)mulsol.i.4.col -e\
			$(TESTPATH)mulsol.i.5.col -e\
			$(TESTPATH)myciel3.col -e\
			$(TESTPATH)myciel4.col -e\
			$(TESTPATH)myciel5.col -e\
			$(TESTPATH)myciel6.col -e\
			$(TESTPATH)queen5_5.col -e\
			$(TESTPATH)queen6_6.col -e\
			$(TESTPATH)queen7_7.col -e\
			$(TESTPATH)queen8_12.col -e\
			$(TESTPATH)queen8_8.col -e\
			$(TESTPATH)queen9_9.col -e\
			$(TESTPATH)queen10_10.col -e\
			$(TESTPATH)queen11_11.col -e\
			$(TESTPATH)queen12_12.col -e\
			$(TESTPATH)queen13_13.col -e\
			$(TESTPATH)queen14_14.col -e\
			$(TESTPATH)queen15_15.col -e\
			$(TESTPATH)r125.1c.col -e\
			$(TESTPATH)r125.1.col -e\
			$(TESTPATH)r125.5.col -e\
			$(TESTPATH)r250.1c.col -e\
			$(TESTPATH)r250.1.col -e\
			$(TESTPATH)r250.5.col -e\
			$(TESTPATH)r1000.1.col -e\
			$(TESTPATH)r1000.5.col -e\
			$(TESTPATH)school1.col -e\
			$(TESTPATH)school1_nsh.col -e\
			$(TESTPATH)will199GPIA.col -e\
			$(TESTPATH)zeroin.i.1.col -e\
			$(TESTPATH)zeroin.i.2.col -e\
			$(TESTPATH)zeroin.i.3.col -e\
			$(TESTPATH)bondy_murty_7.txt -t\
			$(TESTPATH)bondy_murty_11.txt -t\
			$(TESTPATH)bondy_murty_14.txt -t\
			$(TESTPATH)bondy_murty_16.txt -t\
			$(TESTPATH)chvatal_12.txt -t\
			$(TESTPATH)cube_8.txt -t\
			$(TESTPATH)dodecahedron_20.txt -t\
			$(TESTPATH)grotzsch_11.txt -t\
			$(TESTPATH)grunbaum_25.txt -t\
			$(TESTPATH)icosahedron_12.txt -t\
			$(TESTPATH)kuratowski_6.txt -t\
			$(TESTPATH)map_of_india_30.txt -t\
			$(TESTPATH)mycielski_5chromatic_23.txt -t\
			$(TESTPATH)mycielski_6chromatic_47.txt -t\
			$(TESTPATH)mycielski_7chromatic_95.txt -t\
			$(TESTPATH)octahedron_6.txt -t\
			$(TESTPATH)petersen_10.txt -t\
			$(TESTPATH)ramsey_17.txt -t\
			$(TESTPATH)tetrahedron_4.txt -t\
			$(TESTPATH)wheel_8.txt -t

WHEEL=$(TESTPATH)wheel_8.txt -t
